// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvRzW5jLC1G4PQAYogOguZkXl_DGMnHc',
    appId: '1:689610628171:web:a1c0217ed413b0687441ce',
    messagingSenderId: '689610628171',
    projectId: 'tugas1-5ff52',
    authDomain: 'tugas1-5ff52.firebaseapp.com',
    databaseURL: 'https://tugas1-5ff52-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-5ff52.firebasestorage.app',
    measurementId: 'G-9X0CR72YGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfQ2n51-DhOfYftTPTgkHXAZjYNbIHmU',
    appId: '1:689610628171:android:b10f81e61bd358097441ce',
    messagingSenderId: '689610628171',
    projectId: 'tugas1-5ff52',
    databaseURL: 'https://tugas1-5ff52-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-5ff52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8axxAbp1HMvo_RiJ190vsgWGfnoATawE',
    appId: '1:689610628171:ios:39e24fcceaf4a07c7441ce',
    messagingSenderId: '689610628171',
    projectId: 'tugas1-5ff52',
    databaseURL: 'https://tugas1-5ff52-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-5ff52.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8axxAbp1HMvo_RiJ190vsgWGfnoATawE',
    appId: '1:689610628171:ios:39e24fcceaf4a07c7441ce',
    messagingSenderId: '689610628171',
    projectId: 'tugas1-5ff52',
    databaseURL: 'https://tugas1-5ff52-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-5ff52.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvRzW5jLC1G4PQAYogOguZkXl_DGMnHc',
    appId: '1:689610628171:web:c5bcaa1b9321135e7441ce',
    messagingSenderId: '689610628171',
    projectId: 'tugas1-5ff52',
    authDomain: 'tugas1-5ff52.firebaseapp.com',
    databaseURL: 'https://tugas1-5ff52-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-5ff52.firebasestorage.app',
    measurementId: 'G-BVW9WV5SD3',
  );

}