// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjqSBErIMiE4V_3haI-xCE9xX5rVfQ8TI',
    appId: '1:1083530908092:web:10be0d05b19ecfc9175bb9',
    messagingSenderId: '1083530908092',
    projectId: 'tugas1-1d221',
    authDomain: 'tugas1-1d221.firebaseapp.com',
    databaseURL: 'https://tugas1-1d221-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-1d221.firebasestorage.app',
    measurementId: 'G-WK85V6TBHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VT7JdQ53tHvespo49RoAKBNMwYoLh6A',
    appId: '1:1083530908092:android:8a535b5ff7cb83be175bb9',
    messagingSenderId: '1083530908092',
    projectId: 'tugas1-1d221',
    databaseURL: 'https://tugas1-1d221-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-1d221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByqdGxCy7MPOiYgMKuouphmvTj5X7u0J8',
    appId: '1:1083530908092:ios:fd5d264e3ed64fa2175bb9',
    messagingSenderId: '1083530908092',
    projectId: 'tugas1-1d221',
    databaseURL: 'https://tugas1-1d221-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-1d221.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByqdGxCy7MPOiYgMKuouphmvTj5X7u0J8',
    appId: '1:1083530908092:ios:fd5d264e3ed64fa2175bb9',
    messagingSenderId: '1083530908092',
    projectId: 'tugas1-1d221',
    databaseURL: 'https://tugas1-1d221-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-1d221.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjqSBErIMiE4V_3haI-xCE9xX5rVfQ8TI',
    appId: '1:1083530908092:web:ca366b98174d4f97175bb9',
    messagingSenderId: '1083530908092',
    projectId: 'tugas1-1d221',
    authDomain: 'tugas1-1d221.firebaseapp.com',
    databaseURL: 'https://tugas1-1d221-default-rtdb.firebaseio.com',
    storageBucket: 'tugas1-1d221.firebasestorage.app',
    measurementId: 'G-HW7GLCFPTK',
  );

}